[font]

normal = { family = "JetBrainsMonoNerdFontMono" }
size = 18

[keyboard]
bindings = [
  { key = "9", mods = "Control", action = "ResetFontSize"},
  { key = "9", mods = "Control", action = "IncreaseFontSize"},
  { key = "9", mods = "Control", action = "IncreaseFontSize"},
  { key = "9", mods = "Control", action = "IncreaseFontSize"},
  { key = "9", mods = "Control", action = "IncreaseFontSize"},
  { key = "9", mods = "Control", action = "IncreaseFontSize"},
  { key = "9", mods = "Control", action = "IncreaseFontSize"},
  { key = "9", mods = "Control", action = "IncreaseFontSize"},

  { key = "8", mods = "Control", action = "ResetFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"},
  { key = "8", mods = "Control", action = "IncreaseFontSize"}
]

[window]
startup_mode = "Fullscreen"
opacity = 0
